security:
    encoders:
        FOS\UserBundle\Model\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_ADMIN: ROLE_CONTEST_CREATOR
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fosub:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall to allow the frontend to send logs
        frontend_logging:
            pattern: ^/nelmio-js-logger/log$
            security: false

        # Main firewall for the whole site
        main:
            pattern: ^/
            form_login:
                default_target_path: /contests
            remember_me:
                key: %secret%
                lifetime: 1209600 # 2 weeks
                path:     /
            logout: ~
            anonymous: ~
            switch_user: ~

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY } # showcase
        - { path: ^/coming-soon, roles: IS_AUTHENTICATED_ANONYMOUSLY } # showcase
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration/confirm/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contests/(\d+)/invitation/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password-recovery, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
