<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Incenteev\WebBundle\Entity\Periodicity;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121010083959 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE periodicity (id INT AUTO_INCREMENT NOT NULL, days INT NOT NULL, hours INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE contest ADD update_periodicity_id INT NOT NULL, ADD reminder_periodicity_id INT NOT NULL, DROP update_frequency");

        $this->addSql("INSERT INTO periodicity (id, days, hours) SELECT 2 * c.id, ?, ? FROM contest c", array(Periodicity::WEEK_DAYS, Periodicity::HOUR_18));
        $this->addSql("INSERT INTO periodicity (id, days, hours) SELECT 2 * c.id + 1, ?, ? FROM contest c", array(Periodicity::WEEK_DAYS, Periodicity::HOUR_18));
        $this->addSql("UPDATE contest SET update_periodicity_id = 2 * id, reminder_periodicity_id = 2 * id + 1");

        $this->addSql("ALTER TABLE contest ADD CONSTRAINT FK_1A95CB5CDBCF074 FOREIGN KEY (update_periodicity_id) REFERENCES periodicity (id)");
        $this->addSql("ALTER TABLE contest ADD CONSTRAINT FK_1A95CB57821A47F FOREIGN KEY (reminder_periodicity_id) REFERENCES periodicity (id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_1A95CB5CDBCF074 ON contest (update_periodicity_id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_1A95CB57821A47F ON contest (reminder_periodicity_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE contest DROP FOREIGN KEY FK_1A95CB5CDBCF074");
        $this->addSql("ALTER TABLE contest DROP FOREIGN KEY FK_1A95CB57821A47F");
        $this->addSql("DROP TABLE periodicity");
        $this->addSql("DROP INDEX UNIQ_1A95CB5CDBCF074 ON contest");
        $this->addSql("DROP INDEX UNIQ_1A95CB57821A47F ON contest");
        $this->addSql("ALTER TABLE contest ADD update_frequency SMALLINT NOT NULL, DROP update_periodicity_id, DROP reminder_periodicity_id");
        $this->addSql("UPDATE contest SET update_frequency = 1");
    }
}
