<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121001131618 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE comment (id INT AUTO_INCREMENT NOT NULL, thread_id VARCHAR(255) DEFAULT NULL, author_id INT DEFAULT NULL, body LONGTEXT NOT NULL, ancestors VARCHAR(1024) NOT NULL, depth INT NOT NULL, created_at DATETIME NOT NULL, state INT NOT NULL, INDEX IDX_9474526CE2904019 (thread_id), INDEX IDX_9474526CF675F31B (author_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE contest (id INT AUTO_INCREMENT NOT NULL, organization_id INT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, rules LONGTEXT DEFAULT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, update_frequency SMALLINT NOT NULL, unit VARCHAR(255) NOT NULL, data_name VARCHAR(255) NOT NULL, INDEX IDX_1A95CB532C8A3DE (organization_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE contest_user (contest_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_46F8C6821CD0F0DE (contest_id), INDEX IDX_46F8C682A76ED395 (user_id), PRIMARY KEY(contest_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE data_entry (id INT AUTO_INCREMENT NOT NULL, participation_id INT NOT NULL, date DATE NOT NULL, value INT NOT NULL, INDEX IDX_659E51EF6ACE3B73 (participation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE organization (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_C1EE637C5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE participation (id INT AUTO_INCREMENT NOT NULL, contest_id INT NOT NULL, user_id INT NOT NULL, team_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, accepted TINYINT(1) NOT NULL, INDEX IDX_AB55E24F1CD0F0DE (contest_id), INDEX IDX_AB55E24FA76ED395 (user_id), INDEX IDX_AB55E24F296CD8AE (team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE prize (id INT AUTO_INCREMENT NOT NULL, contest_id INT NOT NULL, rank INT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, INDEX IDX_51C88BC11CD0F0DE (contest_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE team (id INT AUTO_INCREMENT NOT NULL, contest_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_C4E0A61F1CD0F0DE (contest_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE thread (id VARCHAR(255) NOT NULL, permalink VARCHAR(255) NOT NULL, is_commentable TINYINT(1) NOT NULL, num_comments INT NOT NULL, last_comment_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, organization_id INT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_1483A5E992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_1483A5E9A0D96FBF (email_canonical), INDEX IDX_1483A5E932C8A3DE (organization_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE comment ADD CONSTRAINT FK_9474526CE2904019 FOREIGN KEY (thread_id) REFERENCES thread (id)");
        $this->addSql("ALTER TABLE comment ADD CONSTRAINT FK_9474526CF675F31B FOREIGN KEY (author_id) REFERENCES users (id)");
        $this->addSql("ALTER TABLE contest ADD CONSTRAINT FK_1A95CB532C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id)");
        $this->addSql("ALTER TABLE contest_user ADD CONSTRAINT FK_46F8C6821CD0F0DE FOREIGN KEY (contest_id) REFERENCES contest (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE contest_user ADD CONSTRAINT FK_46F8C682A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE data_entry ADD CONSTRAINT FK_659E51EF6ACE3B73 FOREIGN KEY (participation_id) REFERENCES participation (id)");
        $this->addSql("ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F1CD0F0DE FOREIGN KEY (contest_id) REFERENCES contest (id)");
        $this->addSql("ALTER TABLE participation ADD CONSTRAINT FK_AB55E24FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)");
        $this->addSql("ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)");
        $this->addSql("ALTER TABLE prize ADD CONSTRAINT FK_51C88BC11CD0F0DE FOREIGN KEY (contest_id) REFERENCES contest (id)");
        $this->addSql("ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F1CD0F0DE FOREIGN KEY (contest_id) REFERENCES contest (id)");
        $this->addSql("ALTER TABLE users ADD CONSTRAINT FK_1483A5E932C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE contest_user DROP FOREIGN KEY FK_46F8C6821CD0F0DE");
        $this->addSql("ALTER TABLE participation DROP FOREIGN KEY FK_AB55E24F1CD0F0DE");
        $this->addSql("ALTER TABLE prize DROP FOREIGN KEY FK_51C88BC11CD0F0DE");
        $this->addSql("ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61F1CD0F0DE");
        $this->addSql("ALTER TABLE contest DROP FOREIGN KEY FK_1A95CB532C8A3DE");
        $this->addSql("ALTER TABLE users DROP FOREIGN KEY FK_1483A5E932C8A3DE");
        $this->addSql("ALTER TABLE data_entry DROP FOREIGN KEY FK_659E51EF6ACE3B73");
        $this->addSql("ALTER TABLE participation DROP FOREIGN KEY FK_AB55E24F296CD8AE");
        $this->addSql("ALTER TABLE comment DROP FOREIGN KEY FK_9474526CE2904019");
        $this->addSql("ALTER TABLE comment DROP FOREIGN KEY FK_9474526CF675F31B");
        $this->addSql("ALTER TABLE contest_user DROP FOREIGN KEY FK_46F8C682A76ED395");
        $this->addSql("ALTER TABLE participation DROP FOREIGN KEY FK_AB55E24FA76ED395");
        $this->addSql("DROP TABLE comment");
        $this->addSql("DROP TABLE contest");
        $this->addSql("DROP TABLE contest_user");
        $this->addSql("DROP TABLE data_entry");
        $this->addSql("DROP TABLE organization");
        $this->addSql("DROP TABLE participation");
        $this->addSql("DROP TABLE prize");
        $this->addSql("DROP TABLE team");
        $this->addSql("DROP TABLE thread");
        $this->addSql("DROP TABLE users");
    }
}
