<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121022160747 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE organization_team (id INT AUTO_INCREMENT NOT NULL, organization_id INT NOT NULL, name VARCHAR(255) NOT NULL, avatar_path VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_FDE9988232C8A3DE (organization_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE organization_team_user (organization_team_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_6445F834E4BE50ED (organization_team_id), INDEX IDX_6445F834A76ED395 (user_id), PRIMARY KEY(organization_team_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE organization_team ADD CONSTRAINT FK_FDE9988232C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id)");
        $this->addSql("ALTER TABLE organization_team_user ADD CONSTRAINT FK_6445F834E4BE50ED FOREIGN KEY (organization_team_id) REFERENCES organization_team (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE organization_team_user ADD CONSTRAINT FK_6445F834A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE organization_team_user DROP FOREIGN KEY FK_6445F834E4BE50ED");
        $this->addSql("DROP TABLE organization_team");
        $this->addSql("DROP TABLE organization_team_user");
    }
}
