<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121120150427 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE participation ADD invited_by_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE participation ADD CONSTRAINT FK_AB55E24FA7B4A7E3 FOREIGN KEY (invited_by_id) REFERENCES users (id)");
        $this->addSql("CREATE INDEX IDX_AB55E24FA7B4A7E3 ON participation (invited_by_id)");
        $this->addSql("ALTER TABLE users ADD created_by_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE users ADD CONSTRAINT FK_1483A5E9B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)");
        $this->addSql("CREATE INDEX IDX_1483A5E9B03A8386 ON users (created_by_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE participation DROP FOREIGN KEY FK_AB55E24FA7B4A7E3");
        $this->addSql("DROP INDEX IDX_AB55E24FA7B4A7E3 ON participation");
        $this->addSql("ALTER TABLE participation DROP invited_by_id");
        $this->addSql("ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9B03A8386");
        $this->addSql("DROP INDEX IDX_1483A5E9B03A8386 ON users");
        $this->addSql("ALTER TABLE users DROP created_by_id");
    }
}
