<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Incenteev\WebBundle\Entity\Periodicity;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121203145635 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE contest ADD summary_periodicity_id INT DEFAULT NULL, CHANGE reminder_periodicity_id reminder_periodicity_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE contest ADD CONSTRAINT FK_1A95CB5982AB811 FOREIGN KEY (summary_periodicity_id) REFERENCES periodicity (id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_1A95CB5982AB811 ON contest (summary_periodicity_id)");
        $this->addSql("ALTER TABLE periodicity ADD weeks INT NOT NULL, ADD guessed TINYINT(1) NOT NULL");
        $this->addSql('UPDATE periodicity SET weeks = ?', array(Periodicity::ALL_WEEKS));
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE contest DROP FOREIGN KEY FK_1A95CB5982AB811");
        $this->addSql("DROP INDEX UNIQ_1A95CB5982AB811 ON contest");
        $this->addSql("ALTER TABLE contest DROP summary_periodicity_id, CHANGE reminder_periodicity_id reminder_periodicity_id INT NOT NULL");
        $this->addSql("ALTER TABLE periodicity DROP weeks, DROP guessed");
    }
}
