<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121023153732 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE participation DROP FOREIGN KEY FK_AB55E24F296CD8AE");
        $this->addSql("CREATE TABLE contest_team (id INT AUTO_INCREMENT NOT NULL, contest_id INT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_F8BB6D41CD0F0DE (contest_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE contest_team ADD CONSTRAINT FK_F8BB6D41CD0F0DE FOREIGN KEY (contest_id) REFERENCES contest (id)");
        $this->addSql("DROP TABLE team");
        $this->addSql("DROP INDEX IDX_AB55E24F296CD8AE ON participation");
        $this->addSql("UPDATE participation SET team_id = NULL"); // Remove any associated team as teams are dropped
        $this->addSql("ALTER TABLE participation CHANGE team_id contest_team_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F24340B45 FOREIGN KEY (contest_team_id) REFERENCES contest_team (id)");
        $this->addSql("CREATE INDEX IDX_AB55E24F24340B45 ON participation (contest_team_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE participation DROP FOREIGN KEY FK_AB55E24F24340B45");
        $this->addSql("CREATE TABLE team (id INT AUTO_INCREMENT NOT NULL, contest_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_C4E0A61F1CD0F0DE (contest_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F1CD0F0DE FOREIGN KEY (contest_id) REFERENCES contest (id)");
        $this->addSql("DROP TABLE contest_team");
        $this->addSql("DROP INDEX IDX_AB55E24F24340B45 ON participation");
        $this->addSql("UPDATE participation SET contest_team_id = NULL"); // Remove any associated contest team as contest teams are dropped
        $this->addSql("ALTER TABLE participation CHANGE contest_team_id team_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)");
        $this->addSql("CREATE INDEX IDX_AB55E24F296CD8AE ON participation (team_id)");
    }
}
