<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Incenteev\WebBundle\Entity\Contest;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121018125024 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE contest ADD background_path VARCHAR(255) DEFAULT NULL, ADD theme VARCHAR(255) NOT NULL");
        $this->addSql("UPDATE contest SET theme = ?", array('theme-light'));
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE contest DROP background_path, DROP theme");
    }
}
