<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121017103518 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE contest ADD avatar_path VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE prize CHANGE image avatar_path VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE users ADD avatar_path VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE contest DROP avatar_path");
        $this->addSql("ALTER TABLE prize CHANGE avatar_path image VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE users DROP avatar_path");
    }
}
