<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Incenteev\WebBundle\Entity\Contest;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121129165446 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE contest DROP FOREIGN KEY FK_1A95CB5CDBCF074");
        $this->addSql("DROP INDEX UNIQ_1A95CB5CDBCF074 ON contest");
        $this->addSql('DELETE p FROM periodicity p JOIN contest c ON c.update_periodicity_id = p.id');
        $this->addSql("ALTER TABLE contest ADD granularity VARCHAR(255) NOT NULL, DROP update_periodicity_id, CHANGE start_date start_date DATE DEFAULT NULL, CHANGE end_date end_date DATE DEFAULT NULL");
        $this->addSql('UPDATE contest SET granularity = ?', array(Contest::GRANULARITY_WEEK));
        $this->addSql("ALTER TABLE data_entry CHANGE date date DATE NOT NULL");

        // Aggregate entries per week
        $this->addSql('UPDATE data_entry SET date = DATE_SUB(date, INTERVAL WEEKDAY(date) DAY)');

        $this->addSql("ALTER TABLE data_entry CHANGE value value NUMERIC(15, 5) DEFAULT NULL");
        $this->addSql('UPDATE data_entry SET value = (SELECT total FROM (SELECT SUM(de.value) as total, MIN(de.id) as min_id FROM `data_entry` de GROUP BY de.participation_id, de.date) as tmp WHERE id = min_id)');
        $this->addSql('DELETE FROM data_entry WHERE value IS NULL');
        $this->addSql("ALTER TABLE data_entry CHANGE value value NUMERIC(15, 5) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // WARNING: This migration can be applied down only when you don't have any contest in the database!

        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE contest ADD update_periodicity_id INT NOT NULL, DROP granularity, CHANGE start_date start_date DATETIME DEFAULT NULL, CHANGE end_date end_date DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE contest ADD CONSTRAINT FK_1A95CB5CDBCF074 FOREIGN KEY (update_periodicity_id) REFERENCES periodicity (id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_1A95CB5CDBCF074 ON contest (update_periodicity_id)");
        $this->addSql("ALTER TABLE data_entry CHANGE date date DATETIME NOT NULL");
    }
}
